export EDITOR=vim
export PAGER="less -R"

shopt -s histappend

export HISTCONTROL=ignoreboth
export HISTIGNORE='ls:bg:fg:history'
export HISTTIMEFORMAT='%F %T '
export HISTCONTROL=ignoreboth
export HISTIGNORE='ls:bg:fg:history'
export HISTTIMEFORMAT='%F %T '

alias ll="ls -l"
alias lt="ls -ltr"
alias la="ls -la"
alias vi="vim"
